#pragma config(Sensor, in1,    TurnGyro,       sensorGyro)
#pragma config(Sensor, dgtl1,  BaseLock,       sensorDigitalOut)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, ShooterEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           Intake,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftShooter1,  tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftShooter2,  tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LeftShooter3,  tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LeftDrive,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RightDrive,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightShooter1, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RightShooter2, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RightShooter3, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          Index,         tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#include "GlobalVariables.c"
#include "GyroLib.c"
#include "TBH_Library.c"
#include "Functions.c"
#include "PositionTrackingLibrary.c"
#include "Vex_Competition_Includes.c"

#pragma DebuggerWindows("debugStream")  //Open Debug Stream Window



task autonomous()
{
////// TEST ///////
GoTo(10, 10, 200);



}

task usercontrol()
{
	// Start the flywheel control task
	startTask(FwControlTask);

	bool IntakeButton = false;
	int IntakeSpeed = 0;
	int AutoIndex = 0;
	int AutoIntake = 0;
	int XSpeed = 0;
	int YSpeed = 0;
	int LastX = 0;
	int LastY = 0;
	int XDiff = 0;
	int YDiff = 0;
	while (true)
	{
		//////// DRIVE ////////
		if(abs(vexRT[Ch3]) > 10 || abs(vexRT[Ch4]) > 10 ||
			abs(vexRT[Ch1]) > 10 || abs(vexRT[Ch2]) > 10){
			// Get joysticks
			XSpeed = 0.5*vexRT[Ch2] - vexRT[Ch3];
			YSpeed = 0.5*vexRT[Ch1] - vexRT[Ch4];
			// Calculate the change and save the value
			XDiff = XSpeed - LastX;
			YDiff = YSpeed - LastY;

			// Slew rate limiting
			if(abs(XDiff) > SlewRate){
				if (XDiff > 0)
					XSpeed = LastX + SlewRate;
				else
					XSpeed = LastX - SlewRate;
			}
			else if(abs(YDiff) > SlewRate){
				if (XDiff > 0)
					YSpeed = LastY + SlewRate;
				else
					YSpeed = LastY - SlewRate;
			}
			// Save current speed values
			LastX = XSpeed;
			LastY = YSpeed;
		}
		// Deadband
		else{
			XSpeed = 0;
			XSpeed = 0;
		}
		// Set motor speed
		motor[LeftDrive] = XSpeed + YSpeed;		//((vexRT[Ch2] + vexRT[Ch1])/2 - (vexRT[Ch3] - vexRT[Ch4]));
		motor[RightDrive] = XSpeed - YSpeed;		//((vexRT[Ch2] - vexRT[Ch1])/2 - (vexRT[Ch3] + vexRT[Ch4]));

		//////// SHOOTER ///////
		if( vexRT[ Btn8R ] == 1 )
			FwVelocitySet( 170, 0.47 );
		if( vexRT[ Btn8U ] == 1 )
			FwVelocitySet( 145, 0.47 );
		if( vexRT[ Btn8L ] == 1 )
			FwVelocitySet( 125, 0.39 );
		if( vexRT[ Btn8D ] == 1 ){
			FwVelocitySet( 00, 0 );
			AutoIndex = 0;
			AutoIntake = 0;
		}

		/////// INTAKE ////////
		motor[Intake] = IntakeSpeed+AutoIntake;
		if(vexRT[Btn6U] == 1){
			IntakeSpeed = 127;
		}
		else if(vexRT[Btn6D] == 1){
			if (IntakeSpeed == 127){
				IntakeButton = true;
				AutoIntake = 0;
				IntakeSpeed = 0;
			}
			else {
				if (IntakeButton == false){
					IntakeSpeed = -127;
				}
			}
		}
		else{
			IntakeButton = false;
			if (IntakeSpeed == -127){
				IntakeSpeed = 0;
			}
		}

		/////// INDEXER ////////
		if(vexRT[Btn5U] == 1){
			motor[Index]   = 127;
		}
		else if(vexRT[Btn5D] == 1){
			motor[Index] = -127;
			AutoIntake = 0;
		}
		else {
			motor[Index] = AutoIndex;
		}

		///////////// AUTO FEED CODE /////////////////
		if (vexRT[Btn7U] == 1){
			AutoIndex = 127;
			AutoIntake = 127;
		}//AutoFeed

	}//While
}// Task Main
