#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Shooter1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Shooter2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Index,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RightDrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Shooter3,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Shooter4,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

		////// DRIVE STICK //////
		motor[LeftDrive]  = (vexRT[Ch3]-vexRT[Ch4]);
		motor[RightDrive]   = (vexRT[Ch3]+vexRT[Ch4]);

		// Intake
		if(vexRT[Btn5U] == 1){
			motor[Intake] = 127;
		}
		else if (vexRT[Btn5D] == 1){
			motor[Intake] = -127;
		}
		else{
			motor[Intake] = 0;
		}

		// Idex
		if(vexRT[Btn6U] == 1){
			motor[Index] = 127;
		}
		else if (vexRT[Btn6D] == 1){
			motor[Index] = -127;
		}
		else{
			motor[Index] = 0;
		}

		// Shooter
		if(vexRT[Btn8R] == 1){
			motor[Shooter1] = 127;
			motor[Shooter2] = 127;
			motor[Shooter3] = 127;
			motor[Shooter4] = 127;
		}
		else if(vexRT[Btn8D] == 1){
			motor[Shooter1] = 0;
			motor[Shooter2] = 0;
			motor[Shooter3] = 0;
			motor[Shooter4] = 0;
		}

	}
}
