#pragma config(Sensor, in2,    PT,             sensorPotentiometer)
#pragma config(Motor,  port1,           CenterDrive,   tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RightDrive,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           L1,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           L2,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           L3,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           R1,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           R2,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           R3,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop.l

	while (true){
		if ((vexRT[Btn6D] == 0) && (vexRT[Btn5D] == 0)){
			motor[LeftDrive] = vexRT[Ch3] + vexRT[Ch1];
			motor[RightDrive] = vexRT[Ch3] - vexRT[Ch1];
			motor[CenterDrive] = vexRT[Ch4];
		}
		if ((vexRT[Btn6D] == 1) && (vexRT[Btn5D] == 0)){
			motor[LeftDrive] = vexRT[Ch3 * 1.25] + vexRT[Ch1];
			motor[RightDrive] = vexRT[Ch3 * 1.25] - vexRT[Ch1];
			motor[CenterDrive] = vexRT[Ch4];
		}
		if ((vexRT[Btn5D] == 1) && (vexRT[Btn6D] == 0)){
			motor[LeftDrive] = vexRT[Ch3 * 0.75] + vexRT[Ch1];
			motor[RightDrive] = vexRT[Ch3 * 0.75] - vexRT[Ch1];
			motor[CenterDrive] = vexRT[Ch4];
		}
	}

	if (vexRT[Btn6U] == 1){
		motor[L1] = 127;
		motor[L2] = 127;
		motor[L3] = 127;
		motor[R1] = 127;
		motor[R2] = 127;
		motor[R3] = 127;
	}
	else if (vexRT[Btn5U]){
		motor[L1] = -60;
		motor[L2] = -60;
		motor[L3] = -60;
		motor[R1] = -60;
		motor[R2] = -60;
		motor[R3] = -60;
	}

	if (vexRT[Btn5U] == 1){
		motor[L1] = 95;
		motor[L2] = 95;
		motor[L3] = 95;
		motor[R1] = 95;
		motor[R2] = 95;
		motor[R3] = 95;
		motor[L1] = -60;
		motor[L2] = -60;
		motor[L3] = -60;
		motor[R1] = -60;
		motor[R2] = -60;
		motor[R3] = -60;
	}


}
