#pragma config(Motor,  port2,           w2_front_right, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           w3_back,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           w1_front_left, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void pre_auton(){
	bStopTasksBetweenModes = true;
}

task autonomous(){

}


task usercontrol()
{
	while (true)
	{

		motor[w1_front_left] = -vexRT[Ch4] - (sqrt(3)/2 * vexRT[Ch1]) - vexRT[Ch3];
		motor[w2_front_right] = -vexRT[Ch4] - (sqrt(3)/2 * vexRT[Ch1]) + vexRT[Ch3];
		motor[w3_back] = -vexRT[Ch4] + vexRT[Ch1];

	}
}
