#pragma config(Sensor, in1,    GYRO,           sensorGyro)
#pragma config(Motor,  port2,           BM_MOTOR,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FR_MOTOR,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FL_MOTOR,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	const TVexJoysticks Y_AXIS = Ch3; // y-axis joystick channel
  const TVexJoysticks X_AXIS = Ch4; // x-axis joystick channel
  const TVexJoysticks R_AXIS = Ch1; // rotation joystick channel
  //const tMotors FL_MOTOR = port4; // front-left motor port/name
  //const tMotors FR_MOTOR = port3; // front-right motor port/name
  //const tMotors BM_MOTOR = port2; // back-middle motor port/name
  const tSensors GYRO = in1; // gyroscopic sensor port/name

  bool doUseGyro = false; // enable gyroscopic sensor

  signed byte joyY = 0;
  signed byte joyX = 0;
  signed byte joyR = 0;
  float y = 0;
  float x = 0;
  float t = 0;
  float wheelSpeed[3] = {0, 0, 0};
  float maxSpeed = 0;

  int r = 1;

  while(true)
  {
    // ==== collect joystick & sensor values ====
    joyY = vexRT[Ch4];
    joyX = vexRT[Ch3];
    joyR = vexRT[Ch1];
    if(doUseGyro)
      t = SensorValue[GYRO]/10;

    // ==== adjust for gyro angle ====
    y = joyY*cosDegrees(t) - joyX*sinDegrees(t);
    x = joyY*sinDegrees(t) + joyX*cosDegrees(t);

    // ==== calculate speeds ====
    wheelSpeed[0] = y*sqrt(3)/2 + x/2 + r; // front-left
    wheelSpeed[1] = y*sqrt(3)/2 - x/2 - r; // front-right
    wheelSpeed[2] = x - r; // back-middle

    // ==== normalize ====
    for (ubyte i=0; i<3; i++)
      if (abs(wheelSpeed[i]) > maxSpeed)
        maxSpeed = abs(wheelSpeed[i]);
    for (ubyte i=0; i<3; i++)
      wheelSpeed[i] *= 127/maxSpeed;

    // ==== update motor speeds ====
    motor[FL_MOTOR] = wheelSpeed[0];
    motor[FR_MOTOR] = wheelSpeed[1];
    motor[BM_MOTOR] = wheelSpeed[2];
  }
	}
