#pragma config(Motor,  port2,           Right,         tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Back,          tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Left,          tmotorVex393TurboSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1){
		motor[Left] = -vexRT[Ch4] - vexRT[Ch3] - (sqrt(3)/2*vexRT[Ch1]);
		motor[Right] = -vexRT[Ch4] + vexRT[Ch3] - (sqrt(3)/2*vexRT[Ch1]);
		motor[Back] = -vexRT[Ch4] + vexRT[Ch1];
}

}
