#pragma config(Motor,  port2,           Left,          tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           Right,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           Back,          tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1){
		motor[left] =  vexRT[Ch4] - vexRT[Ch3] \
		- (0.3*vexRT[Ch1]);
		motor[Right] = vexRT[Ch4]  + vexRT[Ch3] - (0.3*vexRT[Ch1]);
		motor[Back] = vexRT[Ch4] + vexRT[Ch1];
	}
}
