#pragma config(Motor,  port2,           front_left,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           back_left,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           front_right,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           back_right,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

void pre_auton()
{
  bStopTasksBetweenModes = true;
}


task autonomous()
{
  AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{
  TVexJoysticks x_axis = Ch1;
  TVexJoysticks y_axis = Ch2;
  TVexJoysticks r_axis = Ch4;

  while (true)
  {
  	motor[front_left] = vexRT[y_axis] + vexRT[x_axis] + vexRT[r_axis];
  	motor[front_right] = vexRT[y_axis] - vexRT[x_axis] - vexRT[r_axis];
  	motor[back_left] = vexRT[y_axis] - vexRT[x_axis] + vexRT[r_axis];
  	motor[back_right] = vexRT[y_axis] + vexRT[x_axis] - vexRT[r_axis];

    UserControlCodePlaceholderForTesting();
  }
}
