#pragma config(Sensor, in1,    TurnGyro,       sensorGyro)
#pragma config(Sensor, dgtl6,  ,               sensorDigitalIn)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl10, Index,          sensorTouch)
#pragma config(Sensor, dgtl11, ShooterEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           Intake,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftShooter1,  tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftShooter2,  tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LeftShooter3,  tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LeftDrive,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RightDrive,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightShooter1, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RightShooter2, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RightShooter3, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          Index,         tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//pid speed presets
const int FullCourt = 4500;
const int HalfCourt = 3000;
const int Close = 2000;
int Target = 0;
int RPM = 0;



#pragma platform(VEX)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "PID.c"

#pragma DebuggerWindows("debugStream")  //Open Debug Stream Window


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	startTask(Shooter);
	bool AutoFeed = false;
	bool Stopped = false;
	int AutoIndex;
	int IntakeCycles = 0;
	while (true)
	{
		//////// DRIVE ////////
		if(abs(vexRT[Ch3]) > 10 || abs(vexRT[Ch4]) > 10){
			motor[LeftDrive]  = (vexRT[Ch3] + vexRT[Ch4]);
			motor[RightDrive]   = (vexRT[Ch3] - vexRT[Ch4]);
		}
		else{
			motor[LeftDrive]  = 0;
			motor[RightDrive]  = 0;
		}

		//////// SHOOTER ///////
		if (vexRT(Btn8L) == 1){
			Target = Close;
		}
		else if (vexRT(Btn8U) == 1){
			Target  = HalfCourt;
		}
		else if (vexRT(Btn8R) == 1){
			Target  = FullCourt;
		}
		else if (vexRT(Btn8D) == 1){
			Target  = 0;
		}

		/////// INTAKE ////////
		if(vexRT[Btn6U] == 1){
			motor[Intake]   = 127;
		}
		else if(vexRT[Btn6D] == 1){
			if (IntakeCycles < 500){
				motor[Intake] = 0;
			}
			IntakeCycles++;
			if (IntakeCycles > 500){
				motor[Intake]   = -127;
			}
		}
		else{
			if(IntakeCycles > 250){
				motor[Intake]   = 0;
			}
			IntakeCycles = 0;
		}


		/////// INDEXER ////////
		if(vexRT[Btn5U] == 1){
			motor[Index]   = 127;
		}
		else if(vexRT[Btn5D] == 1){
			motor[Index] = -127;
		}
		else {
			motor[Index] = 0 + AutoIndex;
		}


		///////////// AUTO FEED CODE /////////////////
		if (vexRT[Btn7U] == 1) AutoFeed = true;
		else if (vexRT[Btn7D] == 1) AutoFeed = false;

		if (AutoFeed == true){
			// run intake
			motor[Intake] = 127;
			// feed first ball
			if (Stopped == true){
				Stopped = false;
				while (SensorValue(Index) == 0){ //&& vexRT[Btn7D] != 1
					AutoIndex = 127;
				}
			}
			// feed the rest
			else{
				// at speed
				if (RPM >= Target){
					// Shoot
					while (SensorValue(Index) == 1){ //&& vexRT[Btn7D] != 1
						AutoIndex = 127;
					}
					// Load
					while (SensorValue(Index) == 0){ //&& vexRT[Btn7D] != 1
						AutoIndex = 127;
					}
					// Stop
					AutoIndex = 0;
				}
			}
		}

		else {
			if (Stopped == false){
				AutoIndex = 0;
				motor[Index] = 0;
				motor[Intake] = 0;
				Stopped = true;
			}
		}


	}
}
