#pragma config(Sensor, in1,    BowPot,         sensorPotentiometer)
#pragma config(Sensor, in2,    TurnGyro,       sensorGyro)
#pragma config(Sensor, dgtl1,  TensionEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  Ramps,          sensorDigitalOut)
#pragma config(Sensor, dgtl4,  LiftLeft,       sensorDigitalOut)
#pragma config(Sensor, dgtl5,  LiftRight,      sensorDigitalOut)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, BowEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port1,           Tension,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Left1,         tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           Left2,         tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           Left3,         tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           Right1,        tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           Right2,        tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           Right3,        tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port8,           BowLeft,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           BowRight,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Intake,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "Functions.c"
#include "Auto.c"


void pre_auton()
{
	bStopTasksBetweenModes = true;

}


task autonomous()
{
	// SET WHAT AUTO TO RUN
	int auto = 2;

	if (auto == 0){
		// NOTHING
	}
	else if (auto == 1){
		////// STD AOTU 4 FAR TILE ///////
		FourBall();
	}
	else if (auto == 2){
		// TEST PID FUNCTIONS
		Drive(666);
	}

}




task usercontrol()
{
	startTask(LCD);
	startTask(TensionButtons);
	int IntakeCycles = 0;
	int TurnSpeed = 0;

	while(1==1){

		////// DRIVE STICK //////
		motor[Left1]  = (vexRT[Ch3]+vexRT[Ch4]);
		motor[Left2]  = (vexRT[Ch3]+vexRT[Ch4]);
		motor[Left3]  = (vexRT[Ch3]+vexRT[Ch4]);
		motor[Right1]   = (vexRT[Ch3]-vexRT[Ch4]);
		motor[Right2]   = (vexRT[Ch3]-vexRT[Ch4]);
		motor[Right3]   = (vexRT[Ch3]-vexRT[Ch4]);

		////// Bow //////
		motor[BowLeft]  = (-vexRT[Ch3Xmtr2]);
		motor[BowRight]  = (-vexRT[Ch3Xmtr2]);


		/////// INTAKE ////////
		motor[Intake]  = (vexRT[Ch2Xmtr2]);




		if(vexRT[Btn7U] == 1 && vexRT[Btn7L] == 1){
			SensorValue(Ramps) = 1;
		}
		else if (vexRT[Btn7U] == 1){
			SensorValue(Ramps) = 0;
		}
		else if(vexRT[Btn7R] == 1 && vexRT[Btn7D] == 1){
			SensorValue(LiftLeft) = 1;
			SensorValue(LiftRight) = 1;
		}
		else if (vexRT[Btn7R] == 1){
			SensorValue(LiftLeft) = 0;
			SensorValue(LiftRight) = 0;
		}
	}
}
