#pragma config(Sensor, in1,    BowPot,         sensorPotentiometer)
#pragma config(Sensor, in2,    TurnGyro,       sensorGyro)
#pragma config(Sensor, dgtl1,  TensionEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  Ramps,          sensorDigitalOut)
#pragma config(Sensor, dgtl4,  LiftLeft,       sensorDigitalOut)
#pragma config(Sensor, dgtl5,  LiftRight,      sensorDigitalOut)
#pragma config(Sensor, dgtl6,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl10, BaseLock,       sensorDigitalOut)
#pragma config(Sensor, dgtl11, BowEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port1,           Tension,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Left1,         tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           Left2,         tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           Left3,         tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           Right1,        tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           Right2,        tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           Right3,        tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port8,           BowLeft,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           BowRight,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Intake,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "CompIncludes.c"   //Main competition background code...do not modify!
#include "Functions.c"
#include "Auto.c"

task autonomous()
{

	if (AutoSelect == 0){
		// NOTHING
	}
	else if (AutoSelect == 1){
		////// STD AUTO 4 FAR TILE ///////
		FourBall();
	}
	else if (AutoSelect == 2){
		DriveTest(10000);
	}
	else if (AutoSelect == 3){
		motor[Left1] = 127;
		wait1Msec(1000);
		motor[Left1] = 0;
		motor[Left2] = 127;
		wait1Msec(1000);
		motor[Left2] = 0;
		motor[Left3] = 127;
		wait1Msec(1000);
		motor[Left3] = 0;
		wait1Msec(2000);
		motor[BowLeft] = 127;
		wait1Msec(500);
		motor[BowLeft] = 0;
	}
	else if (AutoSelect == 4){
		motor[Right1] = 127;
		wait1Msec(1000);
		motor[Right1] = 0;
		motor[Right2] = 127;
		wait1Msec(1000);
		motor[Right2] = 0;
		motor[Right3] = 127;
		wait1Msec(1000);
		motor[Right3] = 0;
		wait1Msec(2000);
		motor[BowRight] = 127;
		wait1Msec(500);
		motor[BowRight] = 0;
	}

}




task usercontrol()
{
	startTask(LCD);
	startTask(TensionButtons);
	bool isOn = false;
	bool justPressed = false;
	bool isOn2 = false;
	bool justPressed2 = false;
	int IntakeCycles = 0;
	int BowSpeed = 0;

	while(1==1){

		////// DRIVE STICK //////
		motor[Left1]  = (vexRT[Ch3] + vexRT[Ch4]);
		motor[Left2]  = (vexRT[Ch3] + vexRT[Ch4]);
		motor[Left3]  = (vexRT[Ch3] + vexRT[Ch4]);
		motor[Right1]   = (vexRT[Ch3] - vexRT[Ch4]);
		motor[Right2]   = (vexRT[Ch3] - vexRT[Ch4]);
		motor[Right3]   = (vexRT[Ch3] - vexRT[Ch4]);

		////// Bow //////
		motor[BowLeft]  = (vexRT[Ch2] + BowSpeed);
		motor[BowRight]  = (vexRT[Ch2] + BowSpeed);

		////// DRIVER LOADS ///////
		if (vexRT[Btn5U] == 1){
			if (justPressed == false){
				justPressed = true;
				if (isOn == false){
					BowSpeed = 127;
					isOn = true;
				}
				else if (isOn == true){
					BowSpeed = 0;
					isOn = false;
				}
			}
			else if (justPressed == true){
				// Don't change anything
			}
		}
		else{
			justPressed = false;
		}

		/////// INTAKE ////////
		if(vexRT[Btn6U] == 1){
			motor[Intake]   = 127;
		}
		else if(vexRT[Btn6D] == 1){
			if (IntakeCycles < 500){
				motor[Intake] = 0;
			}
			IntakeCycles++;
			if (IntakeCycles > 500){
				motor[Intake]   = -127;
			}
		}
		else{
			if(IntakeCycles > 250){
				motor[Intake]   = 0;
			}
			IntakeCycles = 0;
		}

		////// BASE LOCKS ///////
		if (vexRT[Btn5D] == 1){
			if (justPressed2 == false){
				justPressed2 = true;
				if (isOn2 == false){
					SensorValue(BaseLock) = 1;
					isOn2 = true;
				}
				else if (isOn2 == true){
					SensorValue(BaseLock) = 0;
					isOn2 = false;
				}
			}
			else if (justPressed2 == true){
				// Don't change anything
			}
		}
		else{
			justPressed2 = false;
		}


		///////// LIFT /////////
		if(vexRT[Btn7U] == 1 && vexRT[Btn7L] == 1){
			SensorValue(Ramps) = 1;
		}
		else if (vexRT[Btn7U] == 1){
			SensorValue(Ramps) = 0;
		}
		else if(vexRT[Btn7R] == 1 && vexRT[Btn7D] == 1){
			SensorValue(LiftLeft) = 1;
			SensorValue(LiftRight) = 1;
		}
		else if (vexRT[Btn7R] == 1){
			SensorValue(LiftLeft) = 0;
			SensorValue(LiftRight) = 0;
		}
	}
}
