#pragma config(Sensor, dgtl11, ShooterEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           Intake,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftShooter1,  tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftShooter2,  tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LeftShooter3,  tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LeftDrive,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RightDrive,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightShooter1, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RightShooter2, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RightShooter3, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          Index,         tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "PID.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	startTask(ShooterRPM);
	int ShooterSpeed = 0;
	int IntakeCycles = 0;
	while (true)
	{
		//////// DRIVE ////////
		if(abs(vexRT[Ch3]) > 10 || abs(vexRT[Ch4]) > 10){
			motor[LeftDrive]  = (vexRT[Ch3] + vexRT[Ch4]);
			motor[RightDrive]   = (vexRT[Ch3] - vexRT[Ch4]);
		}
		else{
			motor[LeftDrive]  = 0;
			motor[RightDrive]  = 0;
		}

		///////// SHOOTER /////////
		motor[LeftShooter1]  = ShooterSpeed;
		motor[LeftShooter2]  = ShooterSpeed;
		motor[LeftShooter3]  = ShooterSpeed;

		motor[RightShooter1]  = ShooterSpeed;
		motor[RightShooter2]  = ShooterSpeed;
		motor[RightShooter3]  = ShooterSpeed;

		if (vexRT(Btn8L) == 1){
			ShooterSpeed  = 50;
		}
		else if (vexRT(Btn8U) == 1){
			ShooterSpeed  = 90;
		}
		else if (vexRT(Btn8R) == 1){
			ShooterSpeed  = 127;
		}
		else if (vexRT(Btn8D) == 1){
			ShooterSpeed  = 0;
		}


		/////// INTAKE ////////
		if(vexRT[Btn6U] == 1){
			motor[Intake]   = 127;
		}
		else if(vexRT[Btn6D] == 1){
			if (IntakeCycles < 500){
				motor[Intake] = 0;
			}
			IntakeCycles++;
			if (IntakeCycles > 500){
				motor[Intake]   = -127;
			}
		}
		else{
			if(IntakeCycles > 250){
				motor[Intake]   = 0;
			}
			IntakeCycles = 0;
		}


		/////// INDEXER ////////
		if(vexRT[Btn5U] == 1){
			motor[Index]   = 127;
		}
		else if(vexRT[Btn5D] == 1){
			motor[Index] = -127;
		}
		else {
			motor[Index] = 0;
		}


		/////// SHOOTER TEST ////////
		if (vexRT[Btn7D] == 1 && vexRT[Btn7L] == 1){
			motor[LeftShooter1] = 127;
		}
		else if (vexRT[Btn6D] == 1 && vexRT[Btn8U] == 1){
			motor[LeftShooter2] = 127;
		}
		else if (vexRT[Btn7D] == 1 && vexRT[Btn8R] == 1){
			motor[LeftShooter3] = 127;
		}
		else if (vexRT[Btn7L] == 1){
			motor[RightShooter1] = 127;
		}
		else if (vexRT[Btn7U] == 1){
			motor[RightShooter2] = 127;
		}
		else if (vexRT[Btn7R] == 1){
			motor[RightShooter3] = 127;
		}



	}
}
