#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, ShooterEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           BLShooter,     tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           RightDrive,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Index,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           MLShooter,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           MRShooter,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           TLShooter,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           TRShooter,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BRShooter,     tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#include "PID_Library.c"


void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{
	//startTask(autocomp)
	//startTask(skills)

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

//////////Autonomous Competition/////////
void autocomp ()
{
	targetRPM = full;
	wait1Msec(500);
	motor[Intake] = 127;
	motor[Index]   = 127;
	wait1Msec(500);
	motor[Intake] = 0;
	motor[Index]   = 0;
}

/////////Skills Competition/////////
void skills ()
{
	targetRPM = full;
	motor[Intake] = 127;
	motor[Index]   = 127;
	wait1Msec(1000);
	//turnLeft(2, 90, 40);
	//forward(3, 4, 100);
	//turnRight(2, 90, 40);
}

task usercontrol()
{
	// Start the flywheel control task
	startTask(pid);

	// Main user control loop
	while(1)
	{
		// Different speeds set by buttons
		if( vexRT[ Btn8U ] == 1 ) targetRPM = full;
		else if( vexRT[ Btn8L ] == 1 ) targetRPM = half;
		else if( vexRT[ Btn8R ] == 1 ) targetRPM = close;
		else if( vexRT[ Btn8D ] == 1 )targetRPM = 0;

		//////// DRIVE ////////
		if(abs(vexRT[Ch3]) > 20 || abs(vexRT[Ch4]) > 20 ||
			abs(vexRT[Ch1]) > 20 || abs(vexRT[Ch2]) > 20){
			motor[LeftDrive]  = ((vexRT[Ch2] + vexRT[Ch1]) - (vexRT[Ch3] - vexRT[Ch4])/3);
			motor[RightDrive]   = ((vexRT[Ch2] - vexRT[Ch1]) - (vexRT[Ch3] + vexRT[Ch4])/3);
		}
		else{
			motor[LeftDrive]  = 0;
			motor[RightDrive]  = 0;
		}

		/////// INDEXER ////////

		if(vexRT[Btn5U]) motor[Index] = 127;
		else if(vexRT[Btn5D]) motor[Index] = -127;
		else motor[Index] = 0;


		/////// INTAKE ////////
		if(vexRT[Btn6U]) motor[Intake] = 127;
		else if(vexRT[Btn6D]) motor[Intake] = -127;
		else motor[Intake] = 0;

	}

	// Don't hog the cpu :)
	wait1Msec(10);
	//}
}
