#pragma config(Sensor, in1,    TurnGyro,       sensorGyro)
#pragma config(Sensor, in2,    BowPot,         sensorGyro)
#pragma config(Sensor, dgtl1,  TensionEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  Ramps,          sensorDigitalOut)
#pragma config(Sensor, dgtl4,  LiftLeft,       sensorDigitalOut)
#pragma config(Sensor, dgtl5,  LiftRight,      sensorDigitalOut)
#pragma config(Sensor, dgtl6,  RightDrive,     sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  LeftDrive,      sensorQuadEncoder)
#pragma config(Sensor, dgtl10, BaseLock,       sensorDigitalOut)
#pragma config(Sensor, dgtl11, LED,            sensorDigitalOut)
#pragma config(Motor,  port1,           Tension,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Left1,         tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           Left2,         tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           Left3,         tmotorVex393TurboSpeed_MC29, openLoop, driveLeft, encoderPort, dgtl6)
#pragma config(Motor,  port5,           Right1,        tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           Right2,        tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           Right3,        tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight, encoderPort, dgtl8)
#pragma config(Motor,  port8,           BowLeft,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           BowRight,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Intake,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

/// Defult Auto ///
int AutoSelect = 2;

/// Half Court ///
int HalfCourt = 555;


#include "GyroLib.c"
#include "Functions.c"
#include "Auto.c"
#include "Vex_Competition_Includes.c"

task autonomous()
{
	switch(AutoSelect)
	{
		//AUTO SKILLS
	case 1:
		// Skills
		RedSkills();
		break;

		// AUTO ROUTINES
	case 2:
		//BALL AUTO
		Balls(3500);
		break;
	case 3:
		// FrontL
		FrontL();
	case 4:
		// FrontL
		FrontR();
	case 19:
		// LEFT TEST
		LeftTest();
		break;
	case 20:
		// RIGHT TEST
		RightTest();
		break;
	default:
		//NOTHING
	}
	wait1Msec(100000);
}


task usercontrol()
{
	startTask(TensionButtons);
	bool isOn = false;
	bool justPressed = false;
	bool isOn2 = false;
	bool justPressed2 = false;
	bool LowerTension = false;
	bool RaiseTension = false;
	int IntakeCycles = 0;
	int LeftDrive = 0;
	int RightDrive = 0;
	int BowSpeed = 0;

	while(1==1){
		SensorValue[LED] = 0;

		////// DRIVE STICK //////
		LeftDrive  = (vexRT[Ch3] + vexRT[Ch4]);
		RightDrive   = (vexRT[Ch3] - vexRT[Ch4]);
		BaseSpeed(LeftDrive, RightDrive);

		////// Bow //////
		motor[BowLeft]  = (vexRT[Ch2] + BowSpeed);
		motor[BowRight]  = (vexRT[Ch2] + BowSpeed);

		////// DRIVER LOADS ///////
		if (vexRT[Btn5U] == 1){
			if (justPressed == false){
				justPressed = true;
				if (isOn == false){
					BowSpeed = 100;
					isOn = true;
				}
				else if (isOn == true){
					BowSpeed = 0;
					isOn = false;
				}
			}
			else if (justPressed == true){
				// Don't change anything
			}
		}
		else{
			justPressed = false;
		}

		/////// INTAKE ////////
		if(vexRT[Btn6U] == 1){
			motor[Intake]   = 127;
		}
		else if(vexRT[Btn6D] == 1){
			if (IntakeCycles < 500){
				motor[Intake] = 0;
			}
			IntakeCycles++;
			if (IntakeCycles > 500){
				motor[Intake]   = -127;
			}
		}
		else{
			if(IntakeCycles > 250){
				motor[Intake]   = 0;
			}
			IntakeCycles = 0;
		}

		////// BASE LOCKS ///////
		if (vexRT[Btn5D] == 1){
			if (justPressed2 == false){
				justPressed2 = true;
				if (isOn2 == false){
					SensorValue(BaseLock) = 1;
					isOn2 = true;
				}
				else if (isOn2 == true){
					SensorValue(BaseLock) = 0;
					isOn2 = false;
				}
			}
			else if (justPressed2 == true){
				// Don't change anything
			}
		}
		else{
			justPressed2 = false;
		}


		///////// LIFT /////////
		if(vexRT[Btn7U] == 1 && vexRT[Btn7L] == 1){
			SensorValue(Ramps) = 1;
		}
		else if (vexRT[Btn7U] == 1){
			SensorValue(Ramps) = 0;
		}
		else if(vexRT[Btn7R] == 1 && vexRT[Btn7D] == 1){
			SensorValue(LiftLeft) = 1;
			SensorValue(LiftRight) = 1;
		}
		else if (vexRT[Btn7R] == 1){
			SensorValue(LiftLeft) = 0;
			SensorValue(LiftRight) = 0;
		}

		///////// TENSION BUTTONS ////////
		// Zero Tension
		if(vexRT[Btn8U] == 1 && vexRT[Btn8R] == 1){
			motor[Tension] = 0;
			wait1Msec(1000);
			if(vexRT[Btn8U] == 1 && vexRT[Btn8R] == 1){
				SensorValue(TensionEncoder) = 0;
			}
		}
		// Manual Tension
		if(vexRT[Btn8R] == 1){
			motor[Tension]   = 100; //UP
			RaiseTension = false;
			LowerTension = false;
		}
		else if(vexRT[Btn8L] == 1){
			motor[Tension]   = -80; //DOWN
			RaiseTension = false;
			LowerTension = false;
		}

		// Auto Tension buttons
		else if(vexRT[Btn8U] == 1){
			// Lower tension
			RaiseTension = true;
		}
		else if(vexRT[Btn8D] == 1){
			// Lower tension
			LowerTension = true;
		}

		///// AUTO TENSION /////
		if (RaiseTension == true){
			if (SensorValue(TensionEncoder) > 20){
				motor[Tension] = 127;
			}
			//Was above full court
			else if (SensorValue(TensionEncoder) < -20) {
				motor[Tension] = -80;
			}
			else {
				RaiseTension = false;
			}
		}
		else if(LowerTension == true){
			if (SensorValue(TensionEncoder) > HalfCourt - ){
				motor[Tension] = 127;
			}
			//Was above full court
			else if (SensorValue(TensionEncoder) < -20) {
				motor[Tension] = -80;
			}
			else {
				RaiseTension = false;
			}
		}


		while(SensorValue(TensionEncoder) > 0 && vexRT[Btn8R] == 0){
			motor[Tension] = 127;
		}
	}



}
}




////// Set the tension to values while driving //////
task TensionButtons()
{
int DT = HalfCourt;  // wants 625
while(true)
{
	/////// TENSION ///////
	if(vexRT[Btn8U] == 1 && vexRT[Btn8R] == 1){
		motor[Tension] = 0;
		wait1Msec(1000);
		if(vexRT[Btn8U] == 1 && vexRT[Btn8R] == 1){
			SensorValue(TensionEncoder) = 0;
		}
	}
	if(vexRT[Btn8R] == 1){
		motor[Tension]   = 100;
	}
	else if(vexRT[Btn8L] == 1){
		motor[Tension]   = -80;
	}

	else if(vexRT[Btn8U] == 1){
		while(-SensorValue(TensionEncoder) > 0 && vexRT[Btn8R] == 0){
			motor[Tension] = 127;
		}
	}

	else if(vexRT[Btn8D] == 1){
		if (-SensorValue(TensionEncoder) < 15){
			while(-SensorValue(TensionEncoder) < (DT - 20) && vexRT[Btn8R] == 0){
				motor[Tension] = -127;
			}
		}
		else if (-SensorValue(TensionEncoder) > (DT - 240) && -SensorValue(TensionEncoder) < (DT + 120)){
			motor[Tension] = -100;
			wait1Msec(1000);
			motor[Tension] = 0;
		}
		else if (-SensorValue(TensionEncoder) > (DT + 80)){
			while(-SensorValue(TensionEncoder) >  (DT + 5) && vexRT[Btn8R] == 0){
				motor[Tension] = 127;
			}
		}
		else {
			motor[Tension]   = 0;
		}
	}

	else {
		motor[Tension]   = 0;
	}
	wait1Msec(10);

}
}
