#pragma config(Sensor, in1,    TurnGyro,       sensorGyro)
#pragma config(Sensor, dgtl1,  ledSpeed,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  ledFull,        sensorDigitalOut)
#pragma config(Sensor, dgtl3,  ledHalf,        sensorDigitalOut)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, ShooterEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           Intake,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftShooter1,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftShooter2,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LeftShooter3,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LeftDrive,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RightDrive,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightShooter1, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RightShooter2, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RightShooter3, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          Index,         tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#include "PID_Library.c"

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	startTask( FwControlTask );
	FwVelocitySet( 128, 0.39 );
	wait1Msec(4000);
	motor[Intake] = 127;
	motor[Index]   = 127;
	wait1Msec(4000);
	motor[Intake] = 0;
	motor[Index]   = 0;
	wait1Msec(4000);
	motor[Intake] = 127;
	motor[Index]   = 127;

}

task usercontrol()
{
	// Start the flywheel control task
	startTask( pid );

	bool IntakeButton = false;
	int IntakeSpeed = 0;
	int AutoIndex = 0;
	int AutoIntake = 0;


	// Main user control loop
	while(1)
	{


		if (vexRT[Btn8UXmtr2]) targetRPM = full;
		else if (vexRT[Btn8LXmtr2])targetRPM = 1000;
		else if (vexRT[Btn8RXmtr2])targetRPM = half;
		else if (vexRT[Btn8DXmtr2])targetRPM = 0;


		if (vexRT[Btn6UXmtr2]) shooter(vexRT[Ch2Xmtr2]);

		//////// DRIVE ////////
		if(abs(vexRT[Ch3]) > 10 || abs(vexRT[Ch4]) > 10 ||
			abs(vexRT[Ch1]) > 10 || abs(vexRT[Ch2]) > 10){
			motor[LeftDrive]  = ((vexRT[Ch2] + vexRT[Ch1])/2 - (vexRT[Ch3] - vexRT[Ch4]));
			motor[RightDrive]   = ((vexRT[Ch2] - vexRT[Ch1])/2 - (vexRT[Ch3] + vexRT[Ch4]));
		}
		else{
			motor[LeftDrive]  = 0;
			motor[RightDrive]  = 0;
		}

		///////// INTAKE ////////
		if(vexRT[Btn6U])motor[Intake]=127;
		else if(vexRT[Btn6D])motor[Intake]=-127;
		else motor[Intake]=0;


		//motor[Intake] = IntakeSpeed+AutoIntake;
		//if(vexRT[Btn6U] == 1){
		//	IntakeSpeed = 127;
		//}
		//else if(vexRT[Btn6D] == 1){
		//	if (IntakeSpeed == 127){
		//		IntakeButton = true;
		//		AutoIntake = 0;
		//		IntakeSpeed = 0;
		//	}
		//	else {
		//		if (IntakeButton == false){
		//			IntakeSpeed = -127;
		//		}
		//	}
		//}
		//else{
		//	IntakeButton = false;
		//	if (IntakeSpeed == -127){
		//		IntakeSpeed = 0;
		//	}
		//}

		///////// INDEXER ////////


		if(vexRT[Btn5UXmtr2]) motor[Index] = 127;
		else if(vexRT[Btn5DXmtr2]) motor[Index] = -127;
		else motor[Index] = 0;
		//if(vexRT[Btn5UXmtr2] == 1){
		//	motor[Index]   = 127;
		//}
		//else if(vexRT[Btn5DXmtr2] == 1){
		//	motor[Index] = -127;
		//	AutoIndex = 0;
		//}
		//else {
		//	motor[Index] = AutoIndex;
		//}

		/////////////// AUTO FEED CODE /////////////////
		//if (vexRT[Btn7U] == 1){
		//	AutoIndex = 127;
		//	AutoIntake = 127;
		//}//AutoFeed
		//if(vexRT[Btn7D] == 1){
		//	AutoIndex = 0;
		//	AutoIntake = 0;
		//}

		// Don't hog the cpu :)
		wait1Msec(10);
	}
}
