#pragma config(Sensor, in1,    TurnGyro,       sensorGyro)
#pragma config(Sensor, dgtl1,  ledSpeed,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  ledFull,        sensorDigitalOut)
#pragma config(Sensor, dgtl3,  ledHalf,        sensorDigitalOut)
#pragma config(Sensor, dgtl4,  ball,           sensorDigitalIn)
#pragma config(Sensor, dgtl7,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, ShooterEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           Intake,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftShooter1,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftShooter2,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LeftShooter3,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LeftDrive,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RightDrive,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightShooter1, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RightShooter2, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RightShooter3, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          Index,         tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

// Defult Autonomous
int AutoSelect = 1;

#include "Vex_Competition_Includes1.c"
#include "PID_Library.c"
#include "functions.c"




int lastIntakeState = 0;
int intakeSpeed = 0;
int lastBallState = 1;

void auto (){
	startTask( pid );
	targetRPM = full;

	wait1Msec(3000);

	motor[Intake] = 127;

	while(true){
		motor[Index] = 127;

		while(!((lastBallState != SensorValue[ball]) && SensorValue[ball] == 1)){}
		motor[Index] = 0;
		wait1Msec(1500);

		lastBallState = SensorValue[ball];
	}
}

void skills(){
	int counter = 0;
	startTask( pid );
	targetRPM = skill;

	wait1Msec(3000);

	motor[Intake] = 127;

	while(counter < 39){
		motor[Index] = 127;

		while(!((lastBallState != SensorValue[ball]) && SensorValue[ball] == 1)){}
		motor[Index] = 0;
		wait1Msec(1500);

		lastBallState = SensorValue[ball];
		counter++;
	}

	counter = 0;
	//drive

	while(counter < 39){
		motor[Index] = 127;

		while(!((lastBallState != SensorValue[ball]) && SensorValue[ball] == 1)){}
		motor[Index] = 0;
		wait1Msec(1500);

		lastBallState = SensorValue[ball];
		counter++;
	}
}
void move(){
	motor[LeftDrive] = -100;
	motor[RightDrive] = 120;
	wait1Msec(500);
	motor[LeftDrive] = 0;
	motor[RightDrive] = 0;

	motor[LeftDrive] = -127;
	motor[RightDrive] = -90;
	wait1Msec(1000);
	motor[LeftDrive] = 0;
	motor[RightDrive] = 0;
}

task autonomous()
{
	switch(AutoSelect)
	{
	case 1:
		// Skills
		skills();
		break;

	case 2:
		//BALL AUTO
		auto();
		break;
	case 9:
		//TEST
		break;
	default:
		//NOTHING
	}
	auto();
	//skills();
}

task usercontrol()
{
	// Start the flywheel control task
	startTask( pid );
	targetRPM = 0;

	// Main user control loop
	while(1)
	{
		/////////SHOOTER/////////
		if (vexRT[Btn8UXmtr2]) targetRPM = full;
		else if (vexRT[Btn8LXmtr2]);
		else if (vexRT[Btn8RXmtr2])targetRPM = half;
		else if (vexRT[Btn8DXmtr2])targetRPM = 0;

		if (vexRT[Btn6UXmtr2]) shooter(vexRT[Ch2Xmtr2]);

		//////// DRIVE ////////
		if(abs(vexRT[Ch3]) > 10 || abs(vexRT[Ch4]) > 10 ||
			abs(vexRT[Ch1]) > 10 || abs(vexRT[Ch2]) > 10){
			motor[LeftDrive]  = ((vexRT[Ch2] + vexRT[Ch1])/2 - (vexRT[Ch3] - vexRT[Ch4]));
			motor[RightDrive]   = ((vexRT[Ch2] - vexRT[Ch1])/2 - (vexRT[Ch3] + vexRT[Ch4]));
		}
		else{
			motor[LeftDrive]  = 0;
			motor[RightDrive]  = 0;
		}

		///////// INTAKE ////////

		//Non-Latching
		//if(vexRT[Btn6U])motor[Intake]=127;
		//else if(vexRT[Btn6D])motor[Intake]=-127;
		//else motor[Intake]=0;

		//Latching
		if (vexRT[Btn6U] && vexRT[Btn6U] != lastIntakeState){
			if (intakeSpeed == 0 || intakeSpeed == -127) intakeSpeed = 127;
			else if (intakeSpeed == 127) intakeSpeed = -127;
		}else if (vexRT[Btn6D]) intakeSpeed = 0;

		motor[Intake] = intakeSpeed;

		lastIntakeState = vexRT[Btn6U];

		///////// INDEXER ////////
		if(vexRT[Btn5UXmtr2]) motor[Index] = 127;
		else if(vexRT[Btn5DXmtr2]) motor[Index] = -127;
		else motor[Index] = 0;

		// Don't hog the cpu :)
		wait1Msec(10);

	}
}
