#pragma config(Sensor, in1,    TurnGyro,       sensorGyro)
#pragma config(Sensor, dgtl6,  ,               sensorDigitalIn)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl10, BallLoaded,     sensorTouch)
#pragma config(Sensor, dgtl11, ShooterEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           Intake,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftShooter1,  tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftShooter2,  tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LeftShooter3,  tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LeftDrive,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RightDrive,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightShooter1, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RightShooter2, tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RightShooter3, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          Index,         tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//pid speed presets
const int FullCourt = 4500;
const int HalfCourt = 3600;
const int Close = 3000;
int Target = 0;
int RPM = 0;
int Guess = 0;



#pragma platform(VEX)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
#include "BangBang.c"

#pragma DebuggerWindows("debugStream")  //Open Debug Stream Window


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	startTask(ShooterBangBang);
	bool AutoFeed = false;
	bool Loaded = false;
	bool pressed;
	int AutoIndex = 0;
	int IntakeCycles = 0;
	while (true)
	{
		//////// DRIVE ////////
		if(abs(vexRT[Ch3]) > 10 || abs(vexRT[Ch4]) > 10){
			motor[LeftDrive]  = (vexRT[Ch3] + vexRT[Ch4]);
			motor[RightDrive]   = (vexRT[Ch3] - vexRT[Ch4]);
		}
		else{
			motor[LeftDrive]  = 0;
			motor[RightDrive]  = 0;
		}

		//////// SHOOTER ///////
		if (vexRT(Btn8L) == 1){
			Target = Close;
		}
		else if (vexRT(Btn8U) == 1){
			Target  = HalfCourt;
		}
		else if (vexRT(Btn8R) == 1){
			Target  = FullCourt;
		}
		else if (vexRT(Btn8D) == 1){
			Target  = 0;
		}

		/////// INTAKE ////////
		if(vexRT[Btn5U] == 1){
			motor[Intake]   = 127;
		}
		else if(vexRT[Btn5D] == 1){
			if (IntakeCycles < 500){
				motor[Intake] = 0;
			}
			IntakeCycles++;
			if (IntakeCycles > 500){
				motor[Intake]   = -127;
			}
		}
		else{
			if(IntakeCycles > 250){
				motor[Intake] = 0;
			}
			IntakeCycles = 0;
		}


		/////// INDEXER ////////
		if(vexRT[Btn6U] == 1){
			motor[Index]   = 127;
		}
		else if(vexRT[Btn6D] == 1){
			motor[Index] = -127;
			AutoFeed = false;
		}
		else {
			motor[Index] = AutoIndex;
		}


		//////// SHOOTER GUESS ///////
		if (vexRT(Btn7L) == 1){
			if(pressed == false){
				Guess-=10;
			}
			pressed = true;
		}
		else if (vexRT(Btn7R) == 1){
			if(pressed == false){
				Guess+=10;
			}
			pressed = true;
		}
		else if (vexRT(Btn7D) == 1){
			Guess  = 0;
		}
		else{
			pressed = false;
		}


		///////////// AUTO FEED CODE /////////////////
		if (vexRT[Btn7U] == 1) AutoFeed = true;
		else if (vexRT[Btn7D] == 1) AutoFeed = false;

		if (AutoFeed == true){
			AutoIndex = 127;
		}//AutoFeed


		else {
			AutoIndex = 0;
		}


	}//While
}// Task Main
