#pragma config(Sensor, in1,    pot,            sensorAnalog)
#pragma config(Sensor, dgtl1,  enSh,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  enDr,           sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  ledR,           sensorDigitalOut)
#pragma config(Sensor, dgtl9,  ledY,           sensorDigitalOut)
#pragma config(Sensor, dgtl10, ledG,           sensorDigitalOut)
#pragma config(Sensor, dgtl11, speedLed1,      sensorDigitalOut)
#pragma config(Sensor, dgtl12, speedLed2,      sensorDigitalOut)
#pragma config(Motor,  port1,           intake1,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           shooter1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           shooter2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           shooter3,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           right1,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           right2,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port7,           right3,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port8,           left1,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           left2,         tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          left3,         tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "Motor_Library.c"							//Motor Library

#pragma DebuggerWindows("debugStream")  //Open Debug Stream Window


task pid();
void normAuto();
void proSkill();

//pid speed presets
const int full = 3500;
const int half = 2900;
const int close = 2650;
const int skills = 2950;

//++++++++++++++++++++PID Stuff++++++++++++++++++++
const bool debug = false;

//pid values
const float pVal = 0.7;
//float iVal = 0;
//float dVal = 0;

//PID variables
int error = 0;
//int sumError = 0;
//int slope = 0;
//int lastError = 0;

int pChange = 0;
//int iChange = 0;
//int dChange = 0;
int tChange = 0;

//RPM Calculation Variables
int targetRPM = 0;
int lastVal = 0;
int val = 0;
int diff = 0;
int currentRPM;

task pid(){											//PID task
	while(true){
		if (!vexRT[Btn6UXmtr2]){		//pid overwrite

			//++++++++++++++++++++Current RPM++++++++++++++++++++
			val = SensorValue[enSh];
			diff = val - lastVal;
			currentRPM = diff*10*60*25/360;
			//-----------------End Current RPM ------------------

			//write to debug stream
			if (debug) writeDebugStreamLine("Current RPM: %d", currentRPM);
			if (debug) writeDebugStreamLine("Tagrget RPM: %d", targetRPM);

			//get error
			error = targetRPM - currentRPM;
			if (debug) writeDebugStreamLine("Error: %d", error);
			//sumError = sumError + error;

			//p calculations
			pChange = error * pVal;
			if (debug) writeDebugStreamLine("P Change: %d\n", pChange);

			//i calculations
			//iChange = sumError * iVal;

			//d calculations
			//slope = error - lastError;
			//dChange = slope * dVal;

			//total pid changes
			tChange = pChange; //+ iChange + dChange;

			//make sure motor doesnt run backwards
			if(tChange<0) tChange = 0;

			//update motor
			shooter(tChange);

			//lastError = error;
			lastVal = val;
			wait1Msec(100);

			//led
			if (vexRT[Btn5DXmtr2]){
				if (currentRPM >= targetRPM)speedLed(1);
				else speedLed(0);
			}
			else speedLed(0);

			//speed leds

			if (targetRPM == full) ledRGY(0,1,0);
			else if(targetRPM == half) ledRGY(0,0,1);
			else if (targetRPM == close) ledRGY(1,0,0);
			else if(targetRPM == skills) ledRGY(1,1,1);
			else ledRGY(0,0,0);

		}//over write if
	}//while loop
}//task

//---------------------End PID---------------------


//++++++++++++++++++++Autonomous+++++++++++++++++++
const int intakeTime = 800;
const int moveTime = 3000;
const int autoTargetRPM = close;

void normAuto(){

	startTask(pid);							//start pid
	targetRPM = autoTargetRPM;

	runLeft(123);
	runRight(110);							//move forward a little
	wait1Msec(moveTime);
	moveStright(0);										//stop moving

	moveStright(-50);
	wait1Msec(200);
	moveStright(0);
	wait1Msec(500);

	while (true){
		while(currentRPM < close){}	//wait for shooter to get up to speed
		intake(127);								//run intake
		wait1Msec(intakeTime);			//wait for a second
		intake(0);									//stop intake
	}
}
void proSkill(){
	intake(127);
	startTask(pid);
	targetRPM = skills;

}

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	if (SensorValue[pot] < 2000) proSkill();
	else normAuto();
}

//------------------End Autonomous------------------

task usercontrol()
{
	startTask(pid);

	clearDebugStream();

	while (true)
	{
		//++++++++++++++++++++Shooter++++++++++++++++++++
		if (vexRT[Btn5DXmtr2]){
			if (vexRT[Btn8UXmtr2]) targetRPM = full;
			else if (vexRT[Btn8LXmtr2])targetRPM = skills;
			else if (vexRT[Btn8RXmtr2])targetRPM = half;
			else if (vexRT[Btn8DXmtr2])targetRPM = close;
		}
		else targetRPM = 0;
		if (vexRT[Btn6DXmtr2]) targetRPM = 0;

		//pid overwrite
		if (vexRT[Btn6UXmtr2]) shooter(vexRT[Ch2Xmtr2]);
		//------------------End Shooter------------------

		//+++++++++++++++++++++Drive+++++++++++++++++++++
		if (vexRT[Btn5U]) drive(vexRT[Ch2]/2+vexRT[Ch1]/2,vexRT[Ch2]/2-vexRT[Ch1]/2);
		else if (vexRT[Btn5D]) drive(vexRT[Ch2]/4+vexRT[Ch1]/4,vexRT[Ch2]/4-vexRT[Ch1]/4);
		else drive(vexRT[Ch2]+vexRT[Ch1], vexRT[Ch2]-vexRT[Ch1]);
		/*tank drive
		runLeft(vexRT[Ch3]);
		runRight(vexRT[Ch2]);
		*/
		//--------------------End Drive--------------------

		//++++++++++++++++++++++Intake++++++++++++++++++++++
		if (vexRT[Btn6U]) intake(127);
		else if (vexRT[Btn6D]) intake(-127);
		else intake(0);
		//--------------------End Intake--------------------

		//++++++++++++++++++++Solenoids+++++++++++++++++++++


		//------------------End Solenoids------------------
	}//while
}//task
