#pragma config(Sensor, in1,    TurnGyro,       sensorGyro)
#pragma config(Sensor, dgtl1,  IntakePn,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  BrakePn1,       sensorDigitalOut)
#pragma config(Sensor, dgtl3,  BrakePn2,       sensorDigitalOut)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, ShooterEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           Index,         tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Shooter1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Shooter2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Shooter3,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Shooter4,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LeftDrive1,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           LeftDrive2,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RightDrive1,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RightDrive2,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Intake,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#include "TBH_Library.c"

#pragma DebuggerWindows("debugStream")  //Open Debug Stream Window

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{
	//FwVelocitySet( 115, 0.47 );
	//motor[LeftDrive1]  = -100;
	//motor[RightDrive1]  = -100;
	//motor[LeftDrive2]  = -100;
//	motor[RightDrive2]  = -100;
	//wait1Msec(500);
	//motor[Intake] = 127;
	//motor[Index]   = 127;

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

task usercontrol()
{
	// Start the flywheel control task
	startTask( FwControlTask );

	bool IntakeButton = false;
	int IntakeSpeed = 0;
	int AutoIndex = 0;
	int AutoIntake = 0;


	// Main user control loop
	while(1)
	{
		// Different speeds set by buttons
		if( vexRT[ Btn8R ] == 1 )
			FwVelocitySet( 135, 0.47 ); // Full court
		if( vexRT[ Btn8U ] == 1 )
			FwVelocitySet( 115, 0.47 );
		if( vexRT[ Btn8L ] == 1 )
			FwVelocitySet( 100, 0.39 );
		if( vexRT[ Btn8D ] == 1 ){
			FwVelocitySet( 00, 0 );
			AutoIndex = 0;
			AutoIntake = 0;
		}

		//////// DRIVE ////////
		if(abs(vexRT[Ch3]) > 10 || abs(vexRT[Ch4]) > 10 ||
			abs(vexRT[Ch1]) > 10 || abs(vexRT[Ch2]) > 10){
			motor[LeftDrive1]  = ((vexRT[Ch2] + vexRT[Ch1]) - (vexRT[Ch3] - vexRT[Ch4])/2);
			motor[RightDrive1]   = ((vexRT[Ch2] - vexRT[Ch1]) - (vexRT[Ch3] + vexRT[Ch4])/2);
			motor[LeftDrive2]  = ((vexRT[Ch2] + vexRT[Ch1]) - (vexRT[Ch3] - vexRT[Ch4])/2);
			motor[RightDrive2]   = ((vexRT[Ch2] - vexRT[Ch1]) - (vexRT[Ch3] + vexRT[Ch4])/2);
		}
		else{
			motor[LeftDrive1]  = 0;
			motor[RightDrive1]  = 0;
			motor[LeftDrive2]  = 0;
			motor[RightDrive2]  = 0;
		}

		/////// INTAKE ////////
		motor[Intake] = IntakeSpeed+AutoIntake;
		if(vexRT[Btn6U] == 1){
			IntakeSpeed = 127;
		}
		else if(vexRT[Btn6D] == 1){
			if (IntakeSpeed == 127){
				IntakeButton = true;
				AutoIntake = 0;
				IntakeSpeed = 0;
			}
			else {
				if (IntakeButton == false){
					IntakeSpeed = -127;
				}
			}
		}
		else{
			IntakeButton = false;
			if (IntakeSpeed == -127){
				IntakeSpeed = 0;
			}
		}

		/////////// Pneumatics ////////////
		if(vexRT[Btn7L] == 1){
			SensorValue[IntakePn] = 1;
		}
		else {
			SensorValue[IntakePn] = 0;
		}

		if(vexRT[Btn7R] == 1) {
			SensorValue[BrakePn1] = 1;
		}
		else {
			SensorValue[BrakePn1] = 0;
		}

		/////// INDEXER ////////
		if(vexRT[Btn5U] == 1){
			motor[Index]   = 127;
		}
		else if(vexRT[Btn5D] == 1){
			motor[Index] = -127;
			AutoIntake = 0;
		}
		else {
			motor[Index] = AutoIndex;
		}

		///////////// AUTO FEED CODE /////////////////
		//if (vexRT[Btn7U] == 1){
		//AutoIndex = 127;
		//AutoIntake = 127;
	}//AutoFeed

	// Don't hog the cpu :)
	wait1Msec(10);
	//}
}
