#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, in2,    BowPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl7,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl11, TensionEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           Intake,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftDrive1,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LeftDrive2,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LeftBow1,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           LeftBow2,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightBow2,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           RightBow1,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RightDrive2,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RightDrive1,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Tensioner,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)


/////////// Global Variables //////////////

// Defult Autonomous
int AutoSelect = 1;

// Tension Adjustment
int MidTension = 1600;
int CloseTension = 3500;

// Autofeed
int AutoFeed = 80;

// Position Tracking
int Frame = 2;
float Heading;
float Xpos;
float Ypos;
float Distance;
float DistanceTot;
float StartPositionX;
float StartPositionY;
float StartHeading;


// Files
#include "GyroLib.c"
#include "Functions.c"
#include "PositionLibrary.c"
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!


// AUTO
task autonomous()
{
	startTask(AutoMove);
	// Go to X 3in, Y 2 in, finish with 180 degree angle
	Go(2,3,180);


	// Kill Auto
	stopTask(autonomous);
}

// DRIVER CONTROL
task usercontrol()
{
	int LeftDrive = 0;
	int RightDrive = 0;
	int BowDrive = 0;
	int IntakeSpeed = 0;
	int IntakeButton = 0;
	int TensionSpeed = 0;
	int TensionTarget = 0;
	int Tension = 0;
	int TensionZero = 0;
	int AutoBow = 0;
	bool JustPressed = false;

	while(1==1)
	{
		Tension = SensorValue(TensionEncoder);
		////// DRIVE STICK //////
		if(vexRT(Btn5D) == 1){
			LeftDrive  = (vexRT[Ch3] + vexRT[Ch4])/3;
			RightDrive   = (vexRT[Ch3] - vexRT[Ch4])/3;
		}
		else if(abs(vexRT[Ch3]) > 10 ||abs(vexRT[Ch4]) > 10){
			LeftDrive  = (vexRT[Ch3] + vexRT[Ch4]);
			RightDrive   = (vexRT[Ch3] - vexRT[Ch4]);
		}
		else{
			LeftDrive = 0;
			RightDrive = 0;
		}
		BaseSpeed(LeftDrive, RightDrive);

		////// BOW //////
		if (abs(vexRT[Ch2]) > 10)
			BowDrive = (vexRT[Ch2]);
		else
			BowDrive = 0;

		BowSpeed(BowDrive+AutoBow);

		/////// INTAKE ////////
		if(vexRT[Btn6U] == 1){
			IntakeSpeed = 127;
		}
		else if(vexRT[Btn6D] == 1){
			if (IntakeButton < 20){
				IntakeSpeed = 0;
			}
			IntakeButton++;
			if (IntakeButton > 20){
				IntakeSpeed   = -127;
			}
		}
		else{
			if(IntakeButton > 10){
				IntakeSpeed = 0;
			}
			IntakeButton = 0;
		}
		motor[Intake] = IntakeSpeed;

		////// DRIVER LOADS ///////
		if (vexRT[Btn5U] == 1){
			if (JustPressed == false){
				JustPressed = true;
				if (AutoBow == 0){
					AutoBow = AutoFeed;
				}
				else{
					AutoBow = 0;
				}
			}
		}
		else{
			JustPressed = false;
		}

		//////// TENSION BUTTONS ////////
		if(vexRT[Btn8D] == 1){
			TensionTarget = -1;
			TensionZero++;
			if(vexRT[Btn8L] == 1){
				TensionSpeed = -127;
			}
			else if(vexRT[Btn8R] == 1){
				TensionSpeed = 127;
			}
			else if (TensionZero > 300){
				SensorValue(TensionEncoder) = 0;
			}
		}
		else if(vexRT[Btn8R] == 1){
			TensionTarget = 0;
		}
		else if(vexRT[Btn8U] == 1){
			TensionTarget = MidTension;
		}
		else if(vexRT[Btn8L] == 1){
			TensionTarget = CloseTension;
		}

		/////// TENSIONER ///////
		if(TensionTarget >= 0){
			if (Tension < (TensionTarget)){
				TensionSpeed = -127;
			}
			else if (Tension > (TensionTarget+60)){
				TensionSpeed = 127;
			}
			else {
				TensionTarget = -1;
			}
		}
		//Move tensioner and reset speed
		motor[Tensioner] = TensionSpeed;
		TensionSpeed = 0;

		wait1Msec(10);
	}
}
