#pragma config(Sensor, dgtl11, TensionEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           Intake,        tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftDrive1,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LeftDrive2,    tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LeftBow1,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           LeftBow2,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightBow2,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightBow1,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RightDrive2,   tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           RightDrive1,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Tensioner,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

int MidTension = 500;
int CloseTension = 700;
int AutoSelect = 1;

#include "Functions.c"
#include "GyroLib.c"
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	int LeftDrive = 0;
	int RightDrive = 0;
	int BowDrive = 0;
	int IntakeSpeed = 0;
	int IntakeButton = 0;
	int TensionSpeed = 0;
	int TensionTarget = 0;
	int Tension = 0;
	bool JustPressed = false;

	while(1==1)
	{
		Tension = SensorValue(TensionEncoder);
		////// DRIVE STICK //////
		if(abs(vexRT[Ch3]) > 10 ||abs(vexRT[Ch4]) > 10){
			LeftDrive  = (vexRT[Ch3] - vexRT[Ch4]);
			RightDrive   = (vexRT[Ch3] + vexRT[Ch4]);
		}
		else{
			LeftDrive = 0;
			RightDrive = 0;
		}
		BaseSpeed(LeftDrive, RightDrive);

		////// BOW AND TEST //////
		if (abs(vexRT[Ch2]) > 10)
			BowDrive = (vexRT[Ch2]);
		else
			BowDrive = 0;

		BowSpeed(BowDrive);


		////// INTAKE //////
		if(vexRT[Btn6U] == 1){
			IntakeSpeed = 127;
		}
		else if(vexRT[Btn6D] == 1){
			IntakeButton++;
			if (IntakeButton > 500){
				IntakeSpeed = -127;
			}
			else {
				IntakeSpeed = 0;
			}
		}
		else{
			IntakeButton = 0;
		}
		motor[Intake] = IntakeSpeed;


		/////// TENSION BUTTONS ////////
		if(vexRT[Btn8R] == 1){
			TensionSpeed = 127;
		}
		else if(vexRT[Btn8L] == 1){
			TensionSpeed = -127;
		}
		else {
			TensionSpeed = 0;
		}
		//Move tensioner and reset speed
		motor[Tensioner] = TensionSpeed;
		TensionSpeed = 0;
	}
}
